version: '3'
services:
  web:
    build: .
    container_name: intel-man
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://dlpi:jcg-jlc-lab-1@intelmandb.postgres.database.azure.com:5432/postgres?sslmode=require
