version: '3'
services:
  web:
    build: .
    container_name: intel-man
    ports:
      - "5001:5000"  # Maps host port 5001 to container port 5000
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development